### PR TITLE
htsget service-info markdown [first draft]

### PR DESCRIPTION
**Pull request by mlin**

### CODE REVIEW

**Comment by jb-adams** [comment]
@mlin is it ok to work on consolidating divergences between the OpenAPI and MD here?

I've pushed another [commit](https://github.com/jb-adams/hts-specs/commit/38727a30bdbb4b4cf52d1bcf76017ac3ffc4f06d), which collapses the two separate `service-info` responses into one.

The following misalignment(s) still exist:
1. In the MD, there are 2 `type` properties, one in the root object that says `htsget`, and one within the `htsget` property that states either `reads` or `variants`. In the OpenAPI, there is only 1 `type` property that can have a value of `htsget-reads` or `htsget-variants`.
2. I've stated for both `fieldsParameterEffective` and `tagsParametersEffective` that the property has no bearing on the `variants` endpoint, as the spec doesn't currently delineate the allowed column names as it does for reads. I expect this to change going forward, but should it be left in here for now?

I think that's mostly it. Can you also review the property definitions in the OpenAPI for `formats`, `fieldsParameterEffective` and `tagsParametersEffective` to ensure they don't otherwise contradict what's in the MD?

**Comment by mlin** [comment]
@jb-adams sure, my hope in opening this sub-PR was for it to become part of your https://github.com/samtools/hts-specs/pull/493 when you feel it's ready & consistent

1. I've thought it possible for htsget to eventually provide query access for numerous additional datatypes (e.g. BED, wiggle/bigWig, future graph formats) and thus my instinct is to minimize explicit special-casing for reads & variants to the extent possible. However, this is admittedly an idealistic vision, so if the bifurcation provides more-practical benefits (such as easier OpenAPI capture) then I'm alright with it.
2. I would think `fieldsParameterEffective` and `tagsParametersEffective` would simply always be false for variants endpoints, and don't see further clarification as strictly needed.

**Comment by jb-adams** [comment]
regarding (1), I think the goal with the GA4GH service info endpoint is to provide the client with the API's identity from just the `ServiceType` attribute (ie. `group`, `artifact`, `version`). If `htsget` expands to include additional types at different routes, we could include those on the TASC register at that time. I'm curious to hear what the group thinks.

regarding (2), I've changed the descriptions to align with yours (ie. assume false by default, no explicit mention that this isn't available in variants). Can we change the definitions for `fieldsParameterEffective` and `tagsParametersEffective`, particularly with respect to 'result set filtration'. My understanding is that the results aren't being filtered based on these parameters (ie. like a search filter), but the parameter determines whether the field is emitted (ie. included or excluded). This would bring it more in line with the `fields`, `tags`, and `notags` definitions:

"A list of fields to include, see below. Default: all"
"A comma separated list of tags to include, default: all."
"A comma separated list of tags to exclude, default: none."

**Comment by mlin** [comment]
@jb-adams SGTM -- updated the MD

**Comment by jb-adams** [comment]
Thanks @mlin ! I've merged your MD

**Pull request merged**
